
const api=
[
    { profile:<img src="pic7.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="picb.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
    { profile:<img src="pic1.jpg" width="100%" height="100%" />,
      name:"suraj aravikar",
      user:"@suraj",
      time:"1hr",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic1.jpg"/>,
      id1:100,
      id2:290,
      id3:180,
      id5:10,

    },
    { profile:<img src="pic2.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic2.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
    { profile:<img src="pic3.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic3.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
    { profile:<img src="pic10.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic10.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
    { profile:<img src="pic5.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic5.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
    { profile:<img src="pic6.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic6.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
    { profile:<img src="pic77.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic77.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
    { profile:<img src="pic8.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic8.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
    { profile:<img src="pic9.jpg" width="100%" height="100%" />,
      name:"kajal nimje",
      user:"@kajal nimje 1998",
      time:"6m",
      info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ab quisquam accusantium sapiente sequi nisi, accusamus quo dolorem culpa eligendi sed facilis nesciunt. Explicabo, quas!",
      post:<img src="pic9.jpg"/>,
      id1:100,
      id2:200,
      id3:140,
      id5:10,

    },
];
export default api;
